ekf_filter_node_odom:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    transform_time_offset: 0.0 #TF 변환(map-> odom. odom -> base_linkd)의 타임스탬프를 살짝 미래 시점으로 밀어주는 값
    transform_timeout: 0.0  
    print_diagnostics: true  # EKF 노드가 센서 수신상태, 필터 상태, 시간 지연 문제등을 /diagnostics 토픽으로 퍼블리시    
    publish_tf: false
    
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom


    #wheel odometry 설정 - vx,vy 선속도, vyaw 
    odom0: odometry/wheel
    odom0_config: [false, false, false,
                  false, false, false,
                  true,  true,  false,
                  false, false, true,
                  false, false, false]    
                   
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10



    #IMU 설정 - yaw와 yaw 속도만 사용                #frame_id : base_imu   	IMU frame이 base_link와 다를 경우 static_transform_publisher 필요
    imu0: imu
    imu0_config: [false, false, false,
                  false,  false, true,
                  false, false, false,
                  false,  false,  true,
                  false,   false,  false]

    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    use_control: false       # /cmd_vel 토픽으로부터 가속도항을 추정하여 예측 단계에 사용