navsat_transform_node:
  ros__parameters:
    frequency: 30.0
    delay: 3.0                   #GPS-> UTM 변환을 수행하기 전 기다릴 시간(초단위)
    yaw_offset:  1.570796327              #IMU yaw 기준 보정값(IMU yaw=0 일떄 로봇이 북쪽을 보고 있다면 n/2(=1.5708)로 설정해야 동쪽 기준으로 보정됨)
    magnetic_declination_radians: 0.0
    wait_for_datum: false  # auto-set based on first GPS fix    
    broadcast_utm_transform : false
    publish_filtered_gps: false
    zero_altitude: true
    use_odometry_yaw: false